import {build} from 'esbuild';
import {createHash} from 'node:crypto';
import {readFile,writeFile,mkdir,cp} from 'node:fs/promises';
import {moduleArtifact,safeArtifact} from '../src/chain.mjs';
await writeFile('public-app/abis.json',JSON.stringify({module:moduleArtifact().abi,safe:safeArtifact().abi}));
await mkdir('dist',{recursive:true});
await build({entryPoints:['public-app/app.mjs'],bundle:true,format:'esm',minify:true,outfile:'dist/app.js',target:'es2022',legalComments:'eof'});
let html=await readFile('public/index.html','utf8');
html=html.replaceAll('href="/','href="').replaceAll('src="/','src="');
html=html.replace('href=""','href="./"');
html=html.replace('<title>','<meta name="referrer" content="no-referrer"><meta http-equiv="Content-Security-Policy" content="default-src \'self\'; script-src \'self\'; style-src \'self\'; font-src \'self\'; img-src \'self\' data:; connect-src https://ethereum-sepolia-rpc.publicnode.com; object-src \'none\'; base-uri \'none\'; form-action \'self\'"><title>');
html=html.replaceAll('Local test chain','Ethereum Sepolia').replace('Connecting to the local chain','Reading the Sepolia Safe');
html=html.replace('<button class="secondary" id="refresh">','<button class="secondary" id="connect-owner">Connect owner wallet</button><button class="secondary" id="refresh">');
html=html.replace('Local demonstration. Safe owner and keeper actions use separate local test accounts.','Public testnet workspace. Read receipts without a wallet. Only the configured Safe owner can approve invoices.');
html=html.replace('<button id="sample" class="text-button">','<button id="sample" class="text-button" hidden>');
const releaseConfig=JSON.parse(await readFile('public-app/config.json','utf8'));
if(releaseConfig.keeperLive)html=html.replace('Not connected yet','Sepolia payment verified');
const bundleVersion=createHash('sha256').update(await readFile('dist/app.js')).digest('hex').slice(0,12);
html=html.replace('src="app.js"',`src="app.js?v=${bundleVersion}"`);
await writeFile('dist/index.html',html);
await writeFile('dist/style.css',(await readFile('public/style.css','utf8')).replaceAll("url('/fonts/","url('fonts/"));
await cp('public/fonts','dist/fonts',{recursive:true});await cp('public/favicon.svg','dist/favicon.svg');
await writeFile('dist/.nojekyll','');
console.log('Built static Sepolia workspace. No wallet secret or KeeperHub key is included.');
